<a href="https://colab.research.google.com/github/shoaibjamadar-oss/231A008_NLP_Experiments/blob/main/NLP_exp_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
print("Name:Shoaib Jamadar","UIN:231A008")
documents = [
    "I wonder what movie to watch this weekend.",
    "I hope I did well on today's exam.",
    "I really want to order pizza tonight.",
    "I can't wait for the new movie to release.",
    "I need to finish my assignment before the deadline."
]

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

for i, document in enumerate(documents):
    print(f"D{i+1}: {document}")

Name:Shoaib Jamadar UIN:231A008
D1: I wonder what movie to watch this weekend.
D2: I hope I did well on today's exam.
D3: I really want to order pizza tonight.
D4: I can't wait for the new movie to release.
D5: I need to finish my assignment before the deadline.

In [19]:
print("Name:Shoaib Jamadar","UIN:231A008")
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(documents)
print(tfidf_matrix.shape)

Name:Shoaib Jamadar UIN:231A008
(5, 20)

In [20]:
print("Name:Shoaib Jamadar","UIN:231A008")
print(tfidf_matrix)

Name:Shoaib Jamadar UIN:231A008
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21 stored elements and shape (5, 20)>
  Coords	Values
  (0, 19)	0.5233582502695435
  (0, 6)	0.4222421409859579
  (0, 17)	0.5233582502695435
  (0, 18)	0.5233582502695435
  (1, 5)	0.5
  (1, 2)	0.5
  (1, 13)	0.5
  (1, 3)	0.5
  (2, 11)	0.4472135954999579
  (2, 16)	0.4472135954999579
  (2, 9)	0.4472135954999579
  (2, 10)	0.4472135954999579
  (2, 14)	0.4472135954999579
  (3, 6)	0.4222421409859579
  (3, 15)	0.5233582502695435
  (3, 8)	0.5233582502695435
  (3, 12)	0.5233582502695435
  (4, 7)	0.5
  (4, 4)	0.5
  (4, 0)	0.5
  (4, 1)	0.5

In [21]:
print("Name:Shoaib Jamadar","UIN:231A008")
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=["D1", "D2", "D3", "D4", "D5"]
)

tfidf_df.round(2)

Name:Shoaib Jamadar UIN:231A008

,assignment,deadline,did,exam,finish,hope,movie,need,new,order,pizza,really,release,today,tonight,wait,want,watch,weekend,wonder
D1,0.0,0.0,0.0,0.0,0.0,0.0,0.42,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.52,0.52,0.52
D2,0.0,0.0,0.5,0.5,0.0,0.5,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.5,0.00,0.00,0.00,0.00,0.00,0.00
D3,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.45,0.45,0.45,0.00,0.0,0.45,0.00,0.45,0.00,0.00,0.00
D4,0.0,0.0,0.0,0.0,0.0,0.0,0.42,0.0,0.52,0.00,0.00,0.00,0.52,0.0,0.00,0.52,0.00,0.00,0.00,0.00
D5,0.5,0.5,0.0,0.0,0.5,0.0,0.00,0.5,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00

In [22]:
print("Name:Shoaib Jamadar","UIN:231A008")
print(vectorizer.get_feature_names_out())

Name:Shoaib Jamadar UIN:231A008
['assignment' 'deadline' 'did' 'exam' 'finish' 'hope' 'movie' 'need' 'new'
 'order' 'pizza' 'really' 'release' 'today' 'tonight' 'wait' 'want'
 'watch' 'weekend' 'wonder']

In [11]:
print(len(documents))

5

In [23]:
print("Name:Shoaib Jamadar","UIN:231A008")
similarity_matrix = cosine_similarity(tfidf_matrix)

similarity_matrix

Name:Shoaib Jamadar UIN:231A008

array([[1.        , 0.        , 0.        , 0.17828843, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.17828843, 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

In [24]:
print("Name:Shoaib Jamadar","UIN:231A008")
similarity_df = pd.DataFrame(
similarity_matrix,
index=["D1", "D2", "D3", "D4", "D5"],
columns=["D1", "D2", "D3", "D4", "D5"]
)
similarity_df.round(3)

Name:Shoaib Jamadar UIN:231A008

       D1   D2   D3     D4   D5
D1  1.000  0.0  0.0  0.178  0.0
D2  0.000  1.0  0.0  0.000  0.0
D3  0.000  0.0  1.0  0.000  0.0
D4  0.178  0.0  0.0  1.000  0.0
D5  0.000  0.0  0.0  0.000  1.0

In [25]:
print("Name:Shoaib Jamadar","UIN:231A008")
highest_similarity = -1
most_similar_pair = None

for i in range(len(documents)):
    for j in range(i + 1, len(documents)):

        similarity = similarity_matrix[i][j]

        if similarity > highest_similarity:
            highest_similarity = similarity
            most_similar_pair = (i, j)

print(
    f"Most similar documents: "
    f"D{most_similar_pair[0]+1} and D{most_similar_pair[1]+1}"
)

print(f"Similarity: {highest_similarity:.3f}")

Name:Shoaib Jamadar UIN:231A008
Most similar documents: D1 and D4
Similarity: 0.178